<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.Master" AutoEventWireup="true" CodeBehind="Blood_collection.aspx.cs" Inherits="Blood_Bank_Project.Blood_collection" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="White" BorderStyle="Ridge" BorderWidth="2px" CellPadding="3" CellSpacing="1" DataKeyNames="blood_collection_id" DataSourceID="SqlDataSource1" GridLines="None">
            <Columns>
                <asp:BoundField DataField="blood_collection_id" HeaderText="blood_collection_id" InsertVisible="False" ReadOnly="True" SortExpression="blood_collection_id" />
                <asp:BoundField DataField="donor_id" HeaderText="donor_id" SortExpression="donor_id" />
                <asp:BoundField DataField="hospital" HeaderText="hospital" SortExpression="hospital" />
                <asp:BoundField DataField="blood_group_id" HeaderText="blood_group_id" SortExpression="blood_group_id" />
                <asp:BoundField DataField="no_of_bags" HeaderText="no_of_bags" SortExpression="no_of_bags" />
                <asp:BoundField DataField="date_of_collection" HeaderText="date_of_collection" SortExpression="date_of_collection" />
                <asp:BoundField DataField="nurse_doctor_in_charge" HeaderText="nurse_doctor_in_charge" SortExpression="nurse_doctor_in_charge" />
                <asp:BoundField DataField="remarks" HeaderText="remarks" SortExpression="remarks" />
                <asp:BoundField DataField="user_id" HeaderText="user_id" SortExpression="user_id" />
            </Columns>
            <FooterStyle BackColor="#C6C3C6" ForeColor="Black" />
            <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF" />
            <PagerStyle BackColor="#C6C3C6" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#DEDFDE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#594B9C" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#33276A" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [tbl_blood_collection] WHERE [blood_collection_id] = @blood_collection_id" InsertCommand="INSERT INTO [tbl_blood_collection] ([donor_id], [hospital], [blood_group_id], [no_of_bags], [date_of_collection], [nurse_doctor_in_charge], [remarks], [user_id]) VALUES (@donor_id, @hospital, @blood_group_id, @no_of_bags, @date_of_collection, @nurse_doctor_in_charge, @remarks, @user_id)" SelectCommand="SELECT * FROM [tbl_blood_collection]" UpdateCommand="UPDATE [tbl_blood_collection] SET [donor_id] = @donor_id, [hospital] = @hospital, [blood_group_id] = @blood_group_id, [no_of_bags] = @no_of_bags, [date_of_collection] = @date_of_collection, [nurse_doctor_in_charge] = @nurse_doctor_in_charge, [remarks] = @remarks, [user_id] = @user_id WHERE [blood_collection_id] = @blood_collection_id">
            <DeleteParameters>
                <asp:Parameter Name="blood_collection_id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="donor_id" Type="Int32" />
                <asp:Parameter Name="hospital" Type="String" />
                <asp:Parameter Name="blood_group_id" Type="Int32" />
                <asp:Parameter Name="no_of_bags" Type="Double" />
                <asp:Parameter Name="date_of_collection" Type="DateTime" />
                <asp:Parameter Name="nurse_doctor_in_charge" Type="String" />
                <asp:Parameter Name="remarks" Type="String" />
                <asp:Parameter Name="user_id" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="donor_id" Type="Int32" />
                <asp:Parameter Name="hospital" Type="String" />
                <asp:Parameter Name="blood_group_id" Type="Int32" />
                <asp:Parameter Name="no_of_bags" Type="Double" />
                <asp:Parameter Name="date_of_collection" Type="DateTime" />
                <asp:Parameter Name="nurse_doctor_in_charge" Type="String" />
                <asp:Parameter Name="remarks" Type="String" />
                <asp:Parameter Name="user_id" Type="Int32" />
                <asp:Parameter Name="blood_collection_id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>

    </div>
</asp:Content>
