<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.Master" AutoEventWireup="true" CodeBehind="ViewPatient.aspx.cs" Inherits="Blood_Bank_Project.ViewPatient" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="White" BorderStyle="Ridge" BorderWidth="2px" CellPadding="3" CellSpacing="1" DataKeyNames="recipient_id" DataSourceID="SqlDataSource1" GridLines="None">
            <Columns>
                <asp:BoundField DataField="recipient_id" HeaderText="recipient_id" InsertVisible="False" ReadOnly="True" SortExpression="recipient_id" />
                <asp:BoundField DataField="recipient_complete_name" HeaderText="recipient_complete_name" SortExpression="recipient_complete_name" />
                <asp:BoundField DataField="recipient_photo" HeaderText="recipient_photo" SortExpression="recipient_photo" />
                <asp:BoundField DataField="blood_group_id" HeaderText="blood_group_id" SortExpression="blood_group_id" />
                <asp:BoundField DataField="complete_address" HeaderText="complete_address" SortExpression="complete_address" />
                <asp:BoundField DataField="region" HeaderText="region" SortExpression="region" />
                <asp:BoundField DataField="city" HeaderText="city" SortExpression="city" />
                <asp:BoundField DataField="contact" HeaderText="contact" SortExpression="contact" />
                <asp:BoundField DataField="email_address" HeaderText="email_address" SortExpression="email_address" />
                <asp:BoundField DataField="age" HeaderText="age" SortExpression="age" />
                <asp:BoundField DataField="remarks" HeaderText="remarks" SortExpression="remarks" />
                <asp:BoundField DataField="user_id" HeaderText="user_id" SortExpression="user_id" />
            </Columns>
            <FooterStyle BackColor="#C6C3C6" ForeColor="Black" />
            <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF" />
            <PagerStyle BackColor="#C6C3C6" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#DEDFDE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#594B9C" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#33276A" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [tbl_recipient] WHERE [recipient_id] = @recipient_id" InsertCommand="INSERT INTO [tbl_recipient] ([recipient_complete_name], [recipient_photo], [blood_group_id], [complete_address], [region], [city], [contact], [email_address], [age], [remarks], [user_id]) VALUES (@recipient_complete_name, @recipient_photo, @blood_group_id, @complete_address, @region, @city, @contact, @email_address, @age, @remarks, @user_id)" SelectCommand="SELECT * FROM [tbl_recipient]" UpdateCommand="UPDATE [tbl_recipient] SET [recipient_complete_name] = @recipient_complete_name, [recipient_photo] = @recipient_photo, [blood_group_id] = @blood_group_id, [complete_address] = @complete_address, [region] = @region, [city] = @city, [contact] = @contact, [email_address] = @email_address, [age] = @age, [remarks] = @remarks, [user_id] = @user_id WHERE [recipient_id] = @recipient_id">
            <DeleteParameters>
                <asp:Parameter Name="recipient_id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="recipient_complete_name" Type="String" />
                <asp:Parameter Name="recipient_photo" Type="String" />
                <asp:Parameter Name="blood_group_id" Type="Int32" />
                <asp:Parameter Name="complete_address" Type="String" />
                <asp:Parameter Name="region" Type="String" />
                <asp:Parameter Name="city" Type="String" />
                <asp:Parameter Name="contact" Type="String" />
                <asp:Parameter Name="email_address" Type="String" />
                <asp:Parameter Name="age" Type="Int32" />
                <asp:Parameter Name="remarks" Type="String" />
                <asp:Parameter Name="user_id" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="recipient_complete_name" Type="String" />
                <asp:Parameter Name="recipient_photo" Type="String" />
                <asp:Parameter Name="blood_group_id" Type="Int32" />
                <asp:Parameter Name="complete_address" Type="String" />
                <asp:Parameter Name="region" Type="String" />
                <asp:Parameter Name="city" Type="String" />
                <asp:Parameter Name="contact" Type="String" />
                <asp:Parameter Name="email_address" Type="String" />
                <asp:Parameter Name="age" Type="Int32" />
                <asp:Parameter Name="remarks" Type="String" />
                <asp:Parameter Name="user_id" Type="Int32" />
                <asp:Parameter Name="recipient_id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </div>
</asp:Content>
