<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.Master" AutoEventWireup="true" CodeBehind="ViewDonor.aspx.cs" Inherits="Blood_Bank_Project.ViewDonor" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            margin-right: 154px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container m-3" style="font-family:'Times New Roman';font-size:25px;text-align:center">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="White" BorderStyle="Ridge" BorderWidth="3px" CellPadding="3" CellSpacing="2" DataKeyNames="donor_id" DataSourceID="SqlDataSource1" GridLines="Both" AllowSorting="True" CssClass="auto-style1">
            <Columns>
                <asp:BoundField DataField="donor_id" HeaderText="donor_id" ReadOnly="True" SortExpression="donor_id" />
                <asp:BoundField DataField="donor_name" HeaderText="donor_name" SortExpression="donor_name" />
                <asp:BoundField DataField="donor_photo" HeaderText="donor_photo" SortExpression="donor_photo" />
                <asp:BoundField DataField="blood_group_id" HeaderText="blood_group_id" SortExpression="blood_group_id" />
                <asp:BoundField DataField="complete_address" HeaderText="complete_address" SortExpression="complete_address" />
                <asp:BoundField DataField="region" HeaderText="region" SortExpression="region" />
                <asp:BoundField DataField="city" HeaderText="city" SortExpression="city" />
                <asp:BoundField DataField="contact" HeaderText="contact" SortExpression="contact" />
                <asp:BoundField DataField="email_address" HeaderText="email_address" SortExpression="email_address" />
                <asp:BoundField DataField="age" HeaderText="age" SortExpression="age" />
                <asp:BoundField DataField="remarks" HeaderText="remarks" SortExpression="remarks" />
                <asp:BoundField DataField="user_id" HeaderText="user_id" SortExpression="user_id" />
            </Columns>
            <FooterStyle BackColor="#C6C3C6" ForeColor="Black" />
            <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF" />
            <PagerStyle BackColor="#C6C3C6" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#DEDFDE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#594B9C" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#33276A" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [tbl_donor] WHERE [donor_id] = @donor_id" InsertCommand="INSERT INTO [tbl_donor] ([donor_id], [donor_name], [donor_photo], [blood_group_id], [complete_address], [region], [city], [contact], [email_address], [age], [remarks], [user_id]) VALUES (@donor_id, @donor_name, @donor_photo, @blood_group_id, @complete_address, @region, @city, @contact, @email_address, @age, @remarks, @user_id)" SelectCommand="SELECT * FROM [tbl_donor]" UpdateCommand="UPDATE [tbl_donor] SET [donor_name] = @donor_name, [donor_photo] = @donor_photo, [blood_group_id] = @blood_group_id, [complete_address] = @complete_address, [region] = @region, [city] = @city, [contact] = @contact, [email_address] = @email_address, [age] = @age, [remarks] = @remarks, [user_id] = @user_id WHERE [donor_id] = @donor_id">
            <DeleteParameters>
                <asp:Parameter Name="donor_id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="donor_id" Type="Int32" />
                <asp:Parameter Name="donor_name" Type="String" />
                <asp:Parameter Name="donor_photo" Type="String" />
                <asp:Parameter Name="blood_group_id" Type="Int32" />
                <asp:Parameter Name="complete_address" Type="String" />
                <asp:Parameter Name="region" Type="String" />
                <asp:Parameter Name="city" Type="String" />
                <asp:Parameter Name="contact" Type="String" />
                <asp:Parameter Name="email_address" Type="String" />
                <asp:Parameter Name="age" Type="Int32" />
                <asp:Parameter Name="remarks" Type="String" />
                <asp:Parameter Name="user_id" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="donor_name" Type="String" />
                <asp:Parameter Name="donor_photo" Type="String" />
                <asp:Parameter Name="blood_group_id" Type="Int32" />
                <asp:Parameter Name="complete_address" Type="String" />
                <asp:Parameter Name="region" Type="String" />
                <asp:Parameter Name="city" Type="String" />
                <asp:Parameter Name="contact" Type="String" />
                <asp:Parameter Name="email_address" Type="String" />
                <asp:Parameter Name="age" Type="Int32" />
                <asp:Parameter Name="remarks" Type="String" />
                <asp:Parameter Name="user_id" Type="Int32" />
                <asp:Parameter Name="donor_id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </div>
</asp:Content>
