<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.Master" AutoEventWireup="true" CodeBehind="ViewBloodGroup.aspx.cs" Inherits="Blood_Bank_Project.ViewBloodGroup" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="White" BorderStyle="Ridge" BorderWidth="2px" CellPadding="3" CellSpacing="1" DataKeyNames="blood_group_id" DataSourceID="SqlDataSource1" GridLines="None">
            <Columns>
                <asp:BoundField DataField="blood_group_id" HeaderText="blood_group_id" InsertVisible="False" ReadOnly="True" SortExpression="blood_group_id" />
                <asp:BoundField DataField="blood_group_name" HeaderText="blood_group_name" SortExpression="blood_group_name" />
                <asp:BoundField DataField="description" HeaderText="description" SortExpression="description" />
                <asp:BoundField DataField="user_id" HeaderText="user_id" SortExpression="user_id" />
            </Columns>
            <FooterStyle BackColor="#C6C3C6" ForeColor="Black" />
            <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF" />
            <PagerStyle BackColor="#C6C3C6" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#DEDFDE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#594B9C" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#33276A" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [tbl_blood_group] WHERE [blood_group_id] = @blood_group_id" InsertCommand="INSERT INTO [tbl_blood_group] ([blood_group_name], [description], [user_id]) VALUES (@blood_group_name, @description, @user_id)" SelectCommand="SELECT * FROM [tbl_blood_group]" UpdateCommand="UPDATE [tbl_blood_group] SET [blood_group_name] = @blood_group_name, [description] = @description, [user_id] = @user_id WHERE [blood_group_id] = @blood_group_id">
            <DeleteParameters>
                <asp:Parameter Name="blood_group_id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="blood_group_name" Type="String" />
                <asp:Parameter Name="description" Type="String" />
                <asp:Parameter Name="user_id" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="blood_group_name" Type="String" />
                <asp:Parameter Name="description" Type="String" />
                <asp:Parameter Name="user_id" Type="Int32" />
                <asp:Parameter Name="blood_group_id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </div>
</asp:Content>
