<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.Master" AutoEventWireup="True" CodeBehind="ViewBloodRequest.aspx.cs" Inherits="Blood_Bank_Project.ViewBloodRequest" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="White" BorderStyle="Ridge" BorderWidth="2px" CellPadding="3" CellSpacing="1" DataKeyNames="request_id" DataSourceID="SqlDataSource1" GridLines="None">
            <Columns>
                <asp:BoundField DataField="request_id" HeaderText="request_id" InsertVisible="False" ReadOnly="True" SortExpression="request_id" />
                <asp:BoundField DataField="recipient_id" HeaderText="recipient_id" SortExpression="recipient_id" />
                <asp:BoundField DataField="date_of_request" HeaderText="date_of_request" SortExpression="date_of_request" />
                <asp:BoundField DataField="blood_group" HeaderText="blood_group" SortExpression="blood_group" />
                <asp:BoundField DataField="no_of_bags" HeaderText="no_of_bags" SortExpression="no_of_bags" />
                <asp:BoundField DataField="amount_per_bag" HeaderText="amount_per_bag" SortExpression="amount_per_bag" />
                <asp:BoundField DataField="purpose" HeaderText="purpose" SortExpression="purpose" />
                <asp:BoundField DataField="request_status" HeaderText="request_status" SortExpression="request_status" />
                <asp:BoundField DataField="remarks" HeaderText="remarks" SortExpression="remarks" />
                <asp:BoundField DataField="user_id" HeaderText="user_id" SortExpression="user_id" />
            </Columns>
            <FooterStyle BackColor="#C6C3C6" ForeColor="Black" />
            <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF" />
            <PagerStyle BackColor="#C6C3C6" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#DEDFDE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#594B9C" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#33276A" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [tbl_blood_request] WHERE [request_id] = @request_id" InsertCommand="INSERT INTO [tbl_blood_request] ([recipient_id], [date_of_request], [blood_group], [no_of_bags], [amount_per_bag], [purpose], [request_status], [remarks], [user_id]) VALUES (@recipient_id, @date_of_request, @blood_group, @no_of_bags, @amount_per_bag, @purpose, @request_status, @remarks, @user_id)" SelectCommand="SELECT * FROM [tbl_blood_request]" UpdateCommand="UPDATE [tbl_blood_request] SET [recipient_id] = @recipient_id, [date_of_request] = @date_of_request, [blood_group] = @blood_group, [no_of_bags] = @no_of_bags, [amount_per_bag] = @amount_per_bag, [purpose] = @purpose, [request_status] = @request_status, [remarks] = @remarks, [user_id] = @user_id WHERE [request_id] = @request_id">
            <DeleteParameters>
                <asp:Parameter Name="request_id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="recipient_id" Type="Int32" />
                <asp:Parameter Name="date_of_request" Type="DateTime" />
                <asp:Parameter Name="blood_group" Type="String" />
                <asp:Parameter Name="no_of_bags" Type="Int32" />
                <asp:Parameter Name="amount_per_bag" Type="Double" />
                <asp:Parameter Name="purpose" Type="String" />
                <asp:Parameter Name="request_status" Type="String" />
                <asp:Parameter Name="remarks" Type="String" />
                <asp:Parameter Name="user_id" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="recipient_id" Type="Int32" />
                <asp:Parameter Name="date_of_request" Type="DateTime" />
                <asp:Parameter Name="blood_group" Type="String" />
                <asp:Parameter Name="no_of_bags" Type="Int32" />
                <asp:Parameter Name="amount_per_bag" Type="Double" />
                <asp:Parameter Name="purpose" Type="String" />
                <asp:Parameter Name="request_status" Type="String" />
                <asp:Parameter Name="remarks" Type="String" />
                <asp:Parameter Name="user_id" Type="Int32" />
                <asp:Parameter Name="request_id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </div>
</asp:Content>
